template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "paum1247"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pad"
__UND2C__ = "pad"
__UNDEFINED__ = "Paumarí"
__UND__ = "pad"
