template = "https://github.com/giellalt/template-lang-und"
rev_id = 325
template_sha = "055f523625b4faa95e2b123057d4bd9db38577ef"

[replacements]
__GLOTTOLOG_ID__ = "paum1247"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pad"
__UND2C__ = "pad"
__UNDEFINED__ = "Paumarí"
__UND__ = "pad"
